BQSKit/bqskit

- bqskit/ir/circuit.py
The following example shows the boundary values before and after the bug fix.
```
from bqskit import Circuit
from bqskit.ir.gates.constant.h import HGate
circ = Circuit(3)
circ.append_gate(HGate(), [0])
circ.append_gate(HGate(), [1])
circ.append_gate(HGate(), [0])
circ.append_gate(HGate(), [2])
circ.append_gate(HGate(), [0])
circ.append_gate(HGate(), [1])
circ.append_gate(HGate(), [2])
fold_1 = [(0,0), (0,1)]
fold_2 = [(1,0), (1,2)]
fold_3 = [(2,0), (1,1), (1,2)]
circ.fold(fold_1)
circ.fold(fold_2)
circ.fold(fold_3)
```
KEYWORD BQSKit/bqskit#24
> Fixed boundary calculation bug in the fold method

- bqskit/ir/circuit.py
The `qudits` list in the `batch_pop` method was unsorted, so occasionally when inserting a CircuitGate, the wrong qudits were mapped to. Solves the issue found in KEYWORD #26
> Fixed batch_pop bug

- bqskit/compiler/passes/partitioning/greedy.py
There's no need to figure out the merge stuff, the only thing wrong was that the list of `potential_regions` was sorted least to greatest, and we were picking the smaller regions first instead of the larger ones.
> Fixed bug that selected small regions first

- bqskit/compiler/passes/partitioning/greedy.py
The `bounding_region` for the subsequent calls of `surround` was using an upper bound that was too low, so just single points were being picked out.
> Fixed bounding_region bug

- bqskit/compiler/compiler.py
This fixes a crash that occurred due to the client already being closed in `__exit__` when `Compiler` is used as a context manager, but `close()` is called again in `__del__`. In general `__del__` should not be relied on for resource cleanup, as it may be called at any point after the reference count of an object reaches zero.
We now indicate that users should call `close()` if they do not use the Compiler as a context manager.
> Fix crash in Compiler due to double close

- .pre-commit-config.yaml
A clean `pre-commit run mypy --all-files` takes less than 15 seconds!
> Fix issue with mypy taking too long to run

- README.md
Added a line to ensure readers that this is in fact BSD licensed software so they are not scared off by the rest of the copyright notice.
> Made the copyright section of the README a bit less scary

- bqskit/__init__.py
- bqskit/compiler/compiler.py
- bqskit/compiler/executor.py
- Print an error message when a compiler is created outside of a `if __name__ == '__main__'` clause
- Dask logging is now handled separately from BQSKit logging
- BQSKit logging can be enabled by an exported function now: `bqskit.enable_logging`
> Dask and Logging QOL Improvementes

- bqskit/compiler/compiler.py
- bqskit/runtime/attached.py
- bqskit/runtime/base.py
- bqskit/runtime/detached.py
- bqskit/runtime/manager.py
- bqskit/runtime/worker.py
- setup.cfg
- tests/runtime/test_attached.py
1. No more `if __name_\_ == ...` errors on Windows and Mac
1. Added the `bqskit-worker` entry point, so you can create and control ranks of workers however you would like
1. If you use `bqskit-worker` you can additionally pin the workers to logical CPU ids
> Runtime spawn upgrade

- bqskit/ir/gates/constant/__init__.py
- bqskit/ir/gates/constant/clock.py
- bqskit/ir/gates/constant/csum.py
- bqskit/ir/gates/constant/csumd.py
- bqskit/ir/gates/constant/hd.py
- bqskit/ir/gates/constant/pd.py
- bqskit/ir/gates/constant/shift.py
- bqskit/ir/gates/constant/subswap.py
- bqskit/ir/gates/quditgate.py
closes #153 as part of the UnitaryHack 2023 event. 
**NEW IMPLEMENTATIONS**:
1. a generic `QuditGate` base class (following the examples of `QubitGate` and `QutritGate`)
2. single-qudit Weyl-Heisenberg gates (`ShiftGate` and `ClockGate`)
3. a (Clifford) Hadamard gate `HDGate` (for an *n*-level qudit system)
4. qudit phase gates `PDGate` (related to $\sigma_z$ )
5. a generic (Clifford) CSUM gate `CSUMDGate` (following the [existing implementation in bqskit](https://github.com/BQSKit/bqskit/blob/master/bqskit/ir/gates/constant/csum.py), but generalized to qudits instead of just qutrits)
6. subspace swap gate `SubSwapGate`
Together, the generic `CSUMDGate`, `HDGate`, and `PDGate` s form a universal qudit gate set (proved in [this paper](https://pubs.aip.org/aip/jmp/article/56/3/032202/763827/ …
> adding qudit gates

- bqskit/ir/circuit.py
- bqskit/passes/__init__.py
- bqskit/passes/search/generators/seed.py
- bqskit/passes/synthesis/leap.py
- bqskit/passes/synthesis/qsearch.py
- bqskit/passes/util/__init__.py
- bqskit/passes/util/structure.py
- tests/passes/search/generators/test_seed.py
- tests/passes/synthesis/test_qsearch.py
- tests/passes/util/test_structure.py
Contains changes to the `SeedLayerGenerator` to make going backwards up the synthesis tree possible. Also created a `StructureAnalysisPass` which stores structures in `CircuitGate`s for later analysis. Also contains changes to the `QSearchSynthesisPass` so that seed circuits can be used to accelerate synthesis.
> Seeded synthesis

- bqskit/passes/mapping/embed.py
Need to pass in the model gate set when creating the new graphs in order for the synthesis algorithms to correctly generate layers.
> Small fix to make PAM work for different gate sets

- bqskit/passes/control/foreach.py
- tests/passes/control/test_foreachblock.py
Adding the `pass_down_block_specific_key_prefix` allows for data specific to individual blocks to be put into a `PassData` object. The data associated with this prefix must be a mapping between block indices and block specific data.
For example, one may pass block specific seeds with a dictionary in the form 
`self.pass_down_block_specific_key_prefix + 'seed_circuits' = {block_id: [seed_a, seed_b, ...]}`.
> pass down foreach

- bqskit/utils/math.py
- tests/utils/test_math.py
Adds the `canonical_unitary` function to `bqskit/utils/math.py`. Ensures that unitaries that differ only by a global phase are cast to the same matrix representation.
> Support for Canonical Unitaries

- bqskit/ir/gates/composed/controlled.py
- tests/ir/lang/test_controlled_qasm.py
This PR adds support for outputting qasm of singly-controlled "standard" gates. Standard gates are those that have a defined `qasm_name` property.
Resolves #214
> QASM support for singly-controlled ControlledGates.

- bqskit/passes/search/generators/seed.py
The `hash_structure` function in the `SeedLayerGenerator` assigns a unique hash to each circuit structure. Due to possible mismatches between the 1Q gates used in seed circuits and the 1Q gates used in the internal `layer_gen`, synthesis may revisit the same structure many times.
Example:
A seed circuit with CNOTs at locations [(0,1), (1,2), (1,2)] has U3 gates after each CNOT application. Depending on the layer generator assigned by `_get_layer_gen` in QSearch, multiple 1Q gates may follow each of the U3 gates. These extra 1Q gates impact the circuit structure's hash so that the same structure may be revisited multiple times. This change ensures that only multi-qubit gates are involved in determining the hash of the circuit's structure.
> Hash structure of only multi-qubit gates

- bqskit/passes/search/generators/seed.py
- bqskit/runtime/__init__.py
- bqskit/runtime/worker.py
- tests/runtime/test_cache.py
This PR adds the ability to interact with a "runtime cache" for workers. Objects that are not CPickle-able (such as Pytorch modules) can instead be loaded to cache. Doing so ensures that objects are only loaded by each worker a single time. The cache is implemented as a simple Python dictionary.
Use:
In a worker process, items in worker cache can be accessed using the following general outline:
```
from bqskit.runtime import get_runtime
worker_cache = get_runtime().get_cache()
if 'object_name' not in worker_cache:
object = load_object()
worker_cache['object_name'] = object
else:
object = worker_cache['object_name']
```
> Feature: Cache for runtime workers

- bqskit/compiler/compile.py
- bqskit/passes/retarget/auto.py
- bqskit/passes/retarget/two.py
- tests/compiler/compile/test_corner_cases.py
Fixes #217 by 1) passing synthesis epsilon to the rebasing passes in the standard compilation workflow and 2) detecting identity rebasing and handling it specially.
It seems like our standard numerical instantiation pipelines had particular difficulty solving for the identity in the specific CRY case listed in #217.
> Fix identity rebase

- bqskit/ir/gates/__init__.py
- bqskit/ir/gates/constant/__init__.py
- bqskit/ir/gates/constant/ecr.py
- bqskit/ir/lang/qasm2/visitor.py
- tests/ir/gates/constant/test_ecr.py
- tests/ir/lang/test_qasm_decode.py
Add echoed-resonance (ECR) gate
> Add ECR gate

- bqskit/passes/__init__.py
- bqskit/passes/mapping/__init__.py
- bqskit/passes/mapping/placement/__init__.py
- bqskit/passes/mapping/placement/static.py
- tests/passes/mapping/test_static.py
This PR adds a new pass named `StaticPlacementPass`, which attempts to find an embedding of logical qubits into the physical coupling graph so that no SWAPs are needed.
Also, it supports a `timeout_sec` parameter to limit the search time.
Please note that additional packages such as `timeout_decorator` and `networkx` are required to run this pass.
Original issue: https://github.com/bqskit/bqskit/issues/224
> add StaticPlacementPass

- bqskit/ir/circuit.py
The reason why I considering the node where the score is at least the same with the best score is due to the need to expand the region to at least the number of qubits that we required
Why this works: as the filtering now limit the region to what we want, the node that we assuming should satisfy the filtering and bounded by the region that we want. Therefore, by using union to take into account all regions, we hope to cover the amount of qubits that we want.
After the pair coding session: It seems that the surround function has the bug of not considering the branches that we expect as those points have been examined and had the same score with the best score so far.
> Modifying surround function

- bqskit/runtime/task.py
- bqskit/runtime/worker.py
This is intended to be a simple fix for https://github.com/BQSKit/bqskit/issues/262
Currently, when `RuntimeTask`s are cancelled, they sometimes end up garbage collected with coroutines that are never `await`ed.  When those coroutines get garbage collected, `RuntimeWarning`s appear.
I've implemented `__del__` for `RuntimeTask` which simply `close()`s the coroutine, which lets Python know its ok that the coroutine was never used.
> Implemented `__del__` to clean up hanging coroutines

- bqskit/compiler/compiler.py
This PR updates the exception handling logic in the client-server connection code. Specifically, it modifies how `EOFError` and `ConnectionResetError` are handled during connection failures. The goal is to avoid exception chaining (`from e`) for these specific error types, while maintaining chaining for all other exceptions.
- Added conditional logic to raise `RuntimeError` without from e when the exception is `EOFError` or `ConnectionResetError`.
- For all other exceptions, the existing behavior (raising `RuntimeError` with `from e`) is preserved.
- `EOFError` and `ConnectionResetError `indicate specific situations where the connection is lost in a more predictable way (e.g., server gracfully closing the connection).
- Avoiding exception chaining for these cases provides a clearer stack …
> Handle EOFError and ConnectionResetError without chaining exceptions in server connection failure

- bqskit/compiler/compile.py
- bqskit/compiler/registry.py
- tests/compiler/test_registry.py
This pull request replaces the `_compile_registry` object with type specific registries. This enables default workflows to be registered depending on the type of the target.
Removed
- `_compile_registry`
Added
- `_compile_circuit_registry`, `_compile_unitary_registry`, `_compile_stateprep_registry`, `_compile_statemap_registry`
- `registry_workflow` function now takes as a parameter a target type (`'circuit'`, `'unitary'`, `'stateprep'`, `'statemap'`)
Fixed
- Bug in `bqskit/compiler/compile.py` which always sets the target as `Circuit(1)` for targets of type `UnitaryMatrix`.
> Register workflows by target type

- bqskit/runtime/worker.py
Some more complex instantiation workflows may have several instances of tasks with the same `RuntimeAddress`. In these cases, multiple calls to remove the task associated with the same `RuntimeAddress` may call `Worker._tasks.pop` after it has already been popped. 
Adding a default pop value of `None` avoids raising a `KeyError` in these scenarios.
Fixes #301
> Fix `KeyError` for already popped tasks

- bqskit/ext/qiskit/models.py
This extension ensures that the gate sets of state-of-the-art IBM backends (tested with _quebec_ with gate set `['ecr', 'id', 'rz', 'sx', 'x']`) are supported when the machine model is loaded through `model_from_backend`.
> Extend supported gate sets for qiskit conversion

- bqskit/passes/mapping/topology.py
- bqskit/qis/graph.py
- tests/qis/test_graph.py
Resolves #290.
The issue is that `CouplingGraph` implicitly assumes that qudits are numbered from `0`. This means that any relabeling MUST form a permutation of `[0, |V| - 1]`, otherwise incorrect inferences will be made about the number of qudits and about graph connectivity and so on. I've updated the docstrings and checks to take this into account.
An additional issue is that `relabel_subgraph` allows for such an invalid relabeling which will not throw an error, so I think it would be good to fix that function too while we're at it.
@edyounis
> Deprecate `get_induced_subgraph` and update docstrings for `CouplingGraph` and `get_subgraph`

- bqskit/ir/opt/instantiaters/minimization.py
The multistart instantiation methods were incorrectly comparing residual arrays between starts by only comparing the first element when selecting the best parameters, leading to incorrect parameter selection.
- Added check for `ResidualsFunction` in both `multi_start_instantiate_inplace` and `multi_start_instantiate_async`
- Convert residuals to scalar cost using `HilbertSchmidtCostGenerator` for proper parameter comparison
- Ensures best parameters are selected based on actual cost values rather than just the first residual
- Added imports for `HilbertSchmidtCostGenerator` and `ResidualsFunction`
- Added `isinstance(cost_fn, ResidualsFunction)` check in both multistart methods
- Replaced residuals function with scalar cost function when detected
This fix ensures proper parameter …
> Fix multistart cost comparison for ResidualsFunction
