BQSKit/bqskit

- bqskit/compiler/passes/partitioning/cluster.py
- bqskit/compiler/passes/partitioning/greedy.py
- bqskit/ir/circuit.py
- bqskit/ir/region.py
- tests/compiler/passes/partitioning/test_greedy.py
Rewrote the Greedy Algorithm to use the new CircuitRegion objects. Fixed the bugs associated with it as well.
> New Greedy Algorithm

- bqskit/compiler/passes/synthesis/leap.py
I want to test this more before merging.
> Fix LEAP to match qsearch.

- bqskit/compiler/passes/partitioning/quick.py
- bqskit/ir/region.py
This pass forms partitions in the circuit by iterating over the operations in a topological order and binning them into blocks.
> Add quick partitioner.

- bqskit/qis/unitary/unitarymatrix.py
Added a degree parameter in `UnitaryMatrix.get_distance_from` to allow for easy changing of the Hilbert-Schmidt distance degree.
> Updated `get_distance_from`

- bqskit/compiler/compiler.py
- bqskit/exec/__init__.py
- bqskit/exec/runners/__init__.py
- bqskit/exec/runners/quest.py
- bqskit/passes/__init__.py
- bqskit/passes/control/foreach.py
- bqskit/passes/partitioning/__init__.py
- bqskit/passes/partitioning/single.py
- bqskit/passes/rules/cnot2cz.py
- bqskit/passes/rules/zxzxz.py
- bqskit/passes/search/generators/__init__.py
- bqskit/passes/search/generators/single.py
- tests/passes/partitioning/test_single.py
- tests/passes/rules/test_cnot2cz.py
- tests/passes/rules/test_zxzxz.py
Added a pass to group together single-qubit gates.
> Implemented GroupSingleQuditGatePass Pass

- bqskit/compiler/compiler.py
- bqskit/exec/__init__.py
- bqskit/exec/runners/__init__.py
- bqskit/exec/runners/quest.py
- bqskit/passes/__init__.py
- bqskit/passes/control/foreach.py
- bqskit/passes/partitioning/__init__.py
- bqskit/passes/partitioning/single.py
- bqskit/passes/rules/__init__.py
- bqskit/passes/rules/cnot2cz.py
- bqskit/passes/rules/zxzxz.py
- bqskit/passes/search/generators/__init__.py
- bqskit/passes/search/generators/single.py
- tests/passes/partitioning/test_single.py
- tests/passes/rules/test_cnot2cz.py
- tests/passes/rules/test_zxzxz.py
Implemented the single-qubit ZXZXZ Decomposition and cnot-to-cz conversion rule-based passes. Also created a package to house future rule-based passes.
> Implemented Rule-based Passes

- bqskit/ir/circuit.py
> Minor fix to correctly print the number of qudits

- bqskit/ir/opt/instantiaters/qfactor.py
> Enabling Pickle of QFactor object.

- bqskit/qis/graph.py
Changing the _adj data structure to hold a set of neighbors, and using it while creating the sub graph instead of iterating over all the edges of the graph.
> A faster implementation of the subgraph creation

- bqskit/ir/gates/__init__.py
- bqskit/ir/gates/barrier.py
- bqskit/ir/lang/qasm2/parser.py
- bqskit/ir/lang/qasm2/visitor.py
- bqskit/passes/partitioning/quick.py
- bqskit/passes/partitioning/single.py
- tests/ir/lang/test_qasm_decode.py
- tests/passes/partitioning/test_barrier.py
- tests/passes/partitioning/test_parts.py
Add barrier support to the IR, qasm encode/decode of barriers, and implemented partitioning support for barriers.
> Barrier support

- bqskit/passes/search/generators/fourparam.py
- tests/passes/search/generators/test_four_param.py
> Three cnots in a row

- bqskit/ir/circuit.py
- bqskit/ir/opt/instantiater.py
Changed the instantiation API by moving the multi-start handling from `circuit.instantiate` to the `Instantiater`.
> Update Multistart API

- bqskit/passes/__init__.py
- bqskit/passes/util/__init__.py
- bqskit/passes/util/converttou3.py
- bqskit/passes/util/converttovar.py
- bqskit/passes/util/convertu3tovar.py
- tests/compiler/compile/test_blocked_input.py
- tests/compiler/compile/test_prep.py
- tests/compiler/compile/test_synthesis.py
- tests/conftest.py
- tests/ext/test_pytket.py
- tests/ext/test_qiskit.py
- tests/ir/circuit/test_batch_replace.py
- tests/passes/mapping/test_apply.py
- tests/passes/mapping/test_sabre.py
- tests/passes/partitioning/test_barrier.py
- tests/passes/partitioning/test_cluster.py
- tests/passes/partitioning/test_quick.py
- tests/passes/partitioning/test_scan.py
- tests/passes/partitioning/test_single.py
- tests/passes/processing/test_substitute.py
- tests/passes/rules/test_cnot2cz.py
- tests/passes/synthesis/test_leap.py
- tests/passes/synthesis/test_qfast.py
- tests/passes/synthesis/test_qpredict.py
- tests/passes/synthesis/test_qsearch.py
- tests/passes/util/test_extend.py
- tests/passes/util/test_to_u3.py
- tests/passes/util/test_to_varutry.py
Adding the convert to variable untry pass
Adding test to that pass and also to the toU3 pass
> Add-convert-to-var

- bqskit/compiler/compile.py
- bqskit/passes/processing/rebase.py
This PR removes the need to pass in what gate should be replaced in the rebase pass and replaces every 2-qubit gate in the circuit.
> Basic change to avoid passing in gate to replace

- bqskit/version.py
> Revert "0.4.0b1"

- bqskit/ir/gates/constant/clock.py
- bqskit/ir/gates/constant/csum.py
- bqskit/ir/gates/constant/h.py
- bqskit/ir/gates/constant/pd.py
- bqskit/ir/gates/parameterized/fsim.py
> Gate Documentation Fixes

- bqskit/compiler/compile.py
- bqskit/compiler/machine.py
- bqskit/ext/__init__.py
- docs/index.rst
- docs/source/ext.rst
> Pre built model example

- bqskit/passes/mapping/pam.py
- bqskit/passes/mapping/sabre.py
> Pam barrier fix

- bqskit/qis/unitary/unitary.py
- tests/qis/unitary/test_props.py
> Fixed overflow in Unitary.dim

- bqskit/ir/gates/circuitgate.py
> Fix parameter issue with CircuitGate's QASM

- bqskit/runtime/detached.py
Solving issue #293, by fixing a typo in a variable name
> Solving issue #293

- .github/workflows/tests.yml
- .pre-commit-config.yaml
- README.md
- bqskit/compiler/registry.py
- bqskit/ir/circuit.py
- bqskit/ir/gates/composed/controlled.py
- bqskit/ir/gates/composed/frozenparam.py
- bqskit/ir/gates/constant/csum.py
- bqskit/ir/gates/parameterized/mpry.py
- bqskit/ir/gates/parameterized/mprz.py
- bqskit/ir/operation.py
- bqskit/qis/__init__.py
- bqskit/qis/graph.py
- bqskit/qis/pauli.py
- bqskit/qis/pauliz.py
- bqskit/qis/state/state.py
- bqskit/qis/unitary/unitarybuilder.py
- bqskit/qis/unitary/unitarymatrix.py
- bqskit/utils/math.py
- docs/conf.py
- docs/intro/start.md
- tests/compiler/test_registry.py
- Update and Fix CI Pipeline
- Add support for 3.13
- Drop support for 3.8
> Fix ci precommit

- bqskit/ir/lang/qasm2/parser.py
- tests/ir/lang/test_qasm_decode.py
- Fixes #315 
- Added testers for the fix.
> - Updated `parser.py` to fix #315.

- README.md
- docs/intro/start.md
> Update gov link
